name: docs

on: push
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.10'
    # Standard drop-in approach that should work for most people.
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements-dev.txt
    - name: Building docs
      run: cd docs && make html && cd ..
    # Great extra actions to compose with:
    # Publish built docs to gh-pages branch.
    # ===============================
    - name: Commit documentation changes
      run: |
        git clone https://github.com/coin-or/pulp.git --branch gh-pages --single-branch gh-pages
        rm -rf gh-pages/*
        cp -r docs/build/html/* gh-pages/
        cd gh-pages
        touch .nojekyll
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Update documentation" -a || true
        git push
