name: docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: uv sync --dev
    - name: Building docs
      run: cd docs && uv run make html && cd ..
    - name: Prepare built docs for gh-pages
      run: |
        rm -rf /tmp/docs-html
        cp -r docs/build/html /tmp/docs-html
    - name: Commit documentation changes
      run: |
        git fetch origin gh-pages:gh-pages
        git switch gh-pages || git checkout --orphan gh-pages
        rm -rf *
        cp -r /tmp/docs-html/* .
        touch .nojekyll
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Update documentation" -a || true
    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git push origin gh-pages